services:
  redis:
    image: redis:latest
    ports:
      - "7001:6379"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
