services:
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "7001:6379"
  db:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - '80:80'
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - '3000:3000'